apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-service
  labels:
    app: zipkin-service
spec:
  replicas: 1  # Number of pods to run
  selector:
    matchLabels:
      app: zipkin-service
  template:
    metadata:
      labels:
        app: zipkin-service
    spec:
      containers:
      - name: zipkin-server
        image: openzipkin/zipkin  # Replace with your image name
        ports:
        - containerPort: 9411  # Port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
spec:
  selector:
    app: zipkin-service
  ports:
    - protocol: TCP
      port: 9411  # Port exposed inside the Kubernetes cluster
      targetPort: 9411  # Port Spring Boot app listens on
  type: LoadBalancer  # Internal service (can change to LoadBalancer or NodePort)